# Full list of available options and values:
# - https://stylelint.io/user-guide/example-config/
# - https://stylelint.io/user-guide/rules/
rules:
  at-rule-blacklist: null
  at-rule-empty-line-before: null
  at-rule-name-case: lower
  at-rule-name-newline-after: null
  at-rule-name-space-after: always-single-line
  at-rule-no-unknown: null
  at-rule-no-vendor-prefix: true
  at-rule-semicolon-newline-after: always
  at-rule-semicolon-space-before: never
  at-rule-whitelist: null
  block-closing-brace-empty-line-before: never
  block-closing-brace-newline-after: always-multi-line
  block-closing-brace-newline-before: always-multi-line
  block-closing-brace-space-after: never-single-line
  block-closing-brace-space-before: never-single-line
  block-no-empty: true
  block-opening-brace-newline-after: always-multi-line
  block-opening-brace-newline-before: always-single-line
  block-opening-brace-space-after: never-single-line
  block-opening-brace-space-before: never-single-line
  color-hex-case: lower
  color-hex-length: long
  color-named: [never, { ignore: [inside-function] }]
  color-no-hex: null
  color-no-invalid-hex: true
  comment-empty-line-before: always
  comment-no-empty: true
  comment-whitespace-inside: always
  comment-word-blacklist: null
  custom-media-pattern: null
  custom-property-empty-line-before: never
  custom-property-pattern: null
  declaration-bang-space-after: never
  declaration-bang-space-before: always
  declaration-block-no-duplicate-properties: [true, { ignore: [consecutive-duplicates-with-different-values] }]
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-no-shorthand-property-overrides: true
  declaration-block-semicolon-newline-after: always
  declaration-block-semicolon-newline-before: never-multi-line
  declaration-block-semicolon-space-after: always-single-line
  declaration-block-semicolon-space-before: never
  declaration-block-single-line-max-declarations: 1
  declaration-block-trailing-semicolon: always
  declaration-colon-newline-after: always-multi-line
  declaration-colon-space-after: always
  declaration-colon-space-before: never
  declaration-empty-line-before: never
  declaration-no-important: true
  declaration-property-unit-blacklist: null
  declaration-property-unit-whitelist: null
  declaration-property-value-blacklist: null
  declaration-property-value-whitelist: null
  font-family-name-quotes: always-unless-keyword
  font-family-no-duplicate-names: true
  font-family-no-missing-generic-family-keyword: true
  font-weight-notation: named-where-possible
  function-blacklist: []
  function-calc-no-unspaced-operator: true
  function-comma-newline-after: never-multi-line
  function-comma-newline-before: always-multi-line
  function-comma-space-after: always
  function-linear-gradient-no-nonstandard-direction: true
  function-max-empty-lines: 0
  function-name-case: lower
  function-parentheses-newline-inside: always-multi-line
  function-url-no-scheme-relative: true
  function-url-quotes: always
  function-url-scheme-blacklist: []
  function-url-scheme-whitelist: []
  function-whitelist: null
  function-whitespace-after: always
  indentation: 2
  keyframe-declaration-no-important: true
  length-zero-no-unit: true
  max-empty-lines: 1
  max-line-length: [80, { ignorePattern: ["/^@mixin\\s+/"] }]
  max-nesting-depth: null
  media-feature-colon-space-after: always
  media-feature-colon-space-before: never
  media-feature-name-blacklist: null
  media-feature-name-case: lower
  media-feature-name-no-unknown: true
  media-feature-name-no-vendor-prefix: true
  media-feature-name-whitelist: null
  media-feature-parentheses-space-inside: never
  media-feature-range-operator-space-after: always
  media-feature-range-operator-space-before: always
  media-query-list-comma-newline-after: always-multi-line
  media-query-list-comma-newline-before: never-multi-line
  media-query-list-comma-space-after: always
  media-query-list-comma-space-before: never
  no-descending-specificity: true
  no-duplicate-at-import-rules: true
  no-duplicate-selectors: true
  no-eol-whitespace: null
  no-extra-semicolons: true
  no-invalid-double-slash-comments: null
  no-missing-end-of-source-newline: true
  no-unknown-animations: true
  number-leading-zero: always
  number-max-precision: 3
  number-no-trailing-zeros: true
  property-blacklist: null
  property-case: lower
  property-no-unknown: null
  property-no-vendor-prefix: true
  property-whitelist: null
  rule-empty-line-before: [always, { except: inside-block-and-after-rule }]
  selector-attribute-brackets-space-inside: never
  selector-attribute-operator-blacklist: null
  selector-attribute-operator-space-after: never
  selector-attribute-operator-space-before: never
  selector-attribute-operator-whitelist: null
  selector-attribute-quotes: always
  # https://github.com/bjankord/stylelint-config-sass-guidelines/issues/20#issuecomment-349972873
  selector-class-pattern: ['^(?:(?:o|c|u|t|s|is|has|_|js|qa)-)?[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*(?:__[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:--[a-zA-Z0-9]+(?:-[a-zA-Z0-9]+)*)?(?:\\[.+\\])?$', { resolveNestedSelectors: true }]
  selector-combinator-blacklist: null
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-combinator-whitelist: null
  selector-descendant-combinator-no-non-space: true
  selector-id-pattern: null
  selector-list-comma-newline-after: always
  selector-list-comma-newline-before: never-multi-line
  selector-list-comma-space-after: never-single-line
  selector-list-comma-space-before: never
  selector-max-attribute: 2
  selector-max-class: null
  selector-max-combinators: null
  selector-max-compound-selectors: null
  selector-max-empty-lines: 0
  selector-max-id: 0
  selector-max-pseudo-class: null
  selector-max-specificity: null
  selector-max-type: 1
  selector-max-universal: 1
  selector-nested-pattern: null
  selector-no-qualifying-type: [true, { ignore: [attribute] }]
  selector-no-vendor-prefix: true
  selector-pseudo-class-blacklist: null
  selector-pseudo-class-case: lower
  selector-pseudo-class-no-unknown: true
  selector-pseudo-class-parentheses-space-inside: never
  selector-pseudo-class-whitelist: null
  selector-pseudo-element-blacklist: null
  selector-pseudo-element-case: lower
  selector-pseudo-element-colon-notation: double
  selector-pseudo-element-no-unknown: true
  selector-pseudo-element-whitelist: null
  selector-type-case: lower
  selector-type-no-unknown: null
  shorthand-property-no-redundant-values: true
  string-no-newline: true
  string-quotes: double
  time-min-milliseconds: null
  unit-blacklist: null
  unit-case: lower
  unit-no-unknown: true
  unit-whitelist: ['deg', 'em', 'ex', 'ms', 'rem', '%', 's', 'px', 'vw', 'vh']
  value-keyword-case: lower
  value-list-comma-newline-after: never-multi-line
  value-list-comma-newline-before: never-multi-line
  value-list-comma-space-after: always
  value-list-comma-space-before: never
  value-list-max-empty-lines: 0
  value-no-vendor-prefix: true
